version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./react-project:/usr/src/app
    command:  sh -c "yarn && yarn start"
    ports:
      - "3000:3000"